### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by ymaz** [hiebj/ng-focus-if#12]
Hi, I just spotted that [live demo](http://plnkr.co/edit/MJS3zRk079Mu72o5A9l6?p=preview) is not working anymore, could you please check?

**Comment by hiebj** [comment]
Got it. The problem is that I was linking to raw.githubusercontent.com to include the minified file, and apparently GitHub started setting files hosted from there as `content-type: text/plain` rather than `application/javascript`.

I fixed it by linking the file through the [RawGit](http://www.rawgithub.com) proxy which was created explicitly for this purpose.

**Comment by ymaz** [comment]
@hiebj  thanks!
