### ISSUE TITLE
focus-if should wait for all css animations to complete before firing

### ISSUE THREAD

**Issue by bennypowers** [hiebj/ng-focus-if#21]
I use focus-delay to prevent horrible effects, breaking, calamity, etc when focussing-if inputs on ng-show/statechange/etc. focus-if should know to wait for all animations to finish before firing so that I don't have to manually add in the focus delay.

Great directives thanks for putting them out there.

**Comment by hiebj** [comment]
I initially created some code to attempt this, but the problem is that typically the "animated" element is not the input in question that will receive focus. As such, it's not trivial to figure out where / to which parent the directive would need to attach `animationend` event bindings.

Instead, I suggest you use a strategy like the one I've implemented [here](https://github.com/hiebj/ng-animation-events). Creating new directive(s) that will execute an arbitrary expression when `animationend` events fire will allow you to set a `$scope` value to trigger `focus-if`, without either directive being aware of the other.

**Comment by hiebj** [comment]
Feel free to copy that code. If you think this might be useful to other folks, I'd be happy to publish it on NPM and Bower.
