### ISSUE TITLE
Working Once

### ISSUE THREAD

**Issue by CrackerakiUA** [hiebj/ng-focus-if#22]
I have ng-repeat with inputs and i want focus every time my `focus-if` have `true` inside it. Do i have somehow to unfocus when i am leaving area?

**Comment by nkmdev** [comment]
+1

**Comment by CrackerakiUA** [comment]
Not sure how, but when i moved your directive to the file where i keep my own directives that issue was fixed, didn't change anything on your code.

**Comment by hiebj** [comment]
@CrackerakiUA - I'm not totally sure what the problem was, it certainly doesn't make sense that moving the file should change anything.

**Change detection and the focus callback**

One thing to bear in mind is that `focus-if` can only direct focus to an element when the `$watch` callback is triggered by a change in the evaluated `$watch` expression. It will not continually reapply focus on every digest cycle while the `$watch` expression evaluates as truthy. (See the docs for [$watch](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch) for a detailed explanation of when `$watch` listeners are triggered).

What I mean is, if you are watching a simple `$scope` property like `$scope.shouldFocus`:

```
<input focus-if="shouldFocus" />

$scope.shouldFocus = false; // element is not focused
$scope.shouldFocus = true; // element is focused
... time passes
$scope.shouldFocus = true; // element is NOT focused, the value did not change
$scope.shouldFocus = false;
... digest
$scope.shouldFocus = true; // element is focused again
```

Note that there must be an intervening digest cycle between the `false` and `true` assignments at the end. That is because Angular must first detect that the value was changed to `false`, and then back to `true`. If you make both assignments synchronously, back to back, it will not notice the change. For that reason it is not enough to simply clear the value to `false` and then reset it to `true` immediately afterward when you want to apply focus.

**Option 1: number expression**

One thing you might consider to help with this is to bind the `focus-if` directive to a `$scope` property containing a number. This value is then incremented anytime focus needs to be reapplied. Because the number is different each time, it will trigger the `$watch` callback and reapply focus:

```
<input focus-if="shouldFocus" />

$scope.shouldFocus = 0; // element is not focused
$scope.shouldFocus = 1; // element is focused
... time passes
$scope.shouldFocus = 2; // element is focused again
```

**Option 2: function expression**

Another option is to bind the `focus-if` directive to a function call; e.g.:
`<input focus-if="shouldFocus()" />`
That function can return an arbitrary value based on arbitrary conditions. A truthy return value will trigger focus as long as the value is different from the previous value.

**Option 3: ng-blur**

One final option is to make additional use of [ng-blur](https://docs.angularjs.org/api/ng/directive/ngBlur#!):

```
<input focus-if="shouldFocus" ng-blur="shouldFocus = false" />

$scope.shouldFocus = true; // element is focused
... element is blurred
$scope.shouldFocus = true; // element is focused again
```

This will work in most cases where the only job of `$scope.shouldFocus` is to set focus on the element. However, this is not an effective strategy if the property you are watching is used in some other kind of business logic:
`<input focus-if="modalOpen" ng-blur="modalOpen = false" />`
Obviously that is not a particularly good idea.

**Comment by Jokero** [comment]
Thanks, very helpful
