### ISSUE TITLE
Wrong documentation on npmjs.com

### ISSUE THREAD

**Issue by PierrickGT** [hiebj/ng-focus-if#8]
Hi,

Just a little message to let you know that the documentation of your package on npmjs.com hasn't been updated.

https://www.npmjs.com/package/ng-autofocus

**Comment by hiebj** [comment]
Actually, the reason for that is that I renamed the package. `ng-autofocus` is deprecated, I've been trying to migrate people to `ng-focus-if` (https://www.npmjs.com/package/ng-focus-if).

I tried to publish a change to the README which says in giant bold letters that ng-autofocus is deprecated, but it didn't seem to stick. I "deprecated" the package using npm, but that only causes a warning message in the console during `npm install`.

I hesitate to unpublish `ng-autofocus` because I know people are still using it and I don't want to break people's apps and force them to change their code. I will probably EOL `ng-autofocus` at some point, but I'm not in a hurry to do so.

I will try again to publish a change to `ng-autofocus` so that the documentation has the warning on top.
